import { formatVnd, getProduct, getUnitPrice } from "../../data/products";
import type { CartItem } from "../../types";
import { CartIcon, CheckIcon, ClockIcon, CloseIcon } from "../../shared/icons";
import { QuantityControl } from "../../shared/ui";

export default function CartDrawer({ items, onClose, onQuantity, onRemove, onCheckout }: { items: CartItem[]; onClose: () => void; onQuantity: (key: string, quantity: number) => void; onRemove: (key: string) => void; onCheckout: () => void }) {
  const subtotal = items.reduce((total, item) => { const product = getProduct(item.productId); return product ? total + getUnitPrice(product, item.sizeId, item.toppingIds) * item.quantity : total; }, 0);
  return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside aria-label="Giỏ hàng" className="cart-drawer"><div className="drawer-header"><div><span className="eyebrow"><span /> Đơn của bạn</span><h2>Giỏ hàng <small>{items.reduce((sum, item) => sum + item.quantity, 0)} món</small></h2></div><button aria-label="Đóng giỏ hàng" className="modal-close static" onClick={onClose}><CloseIcon /></button></div>{items.length ? <><div className="cart-items">{items.map((item) => { const product = getProduct(item.productId); if (!product) return null; const toppings = product.toppings.filter((topping) => item.toppingIds.includes(topping.id)); return <article className="cart-item" key={item.key}><img alt="" src={product.imageUrl} /><div className="cart-item-info"><h3>{product.name}</h3><p>Size {item.sizeId}{toppings.length ? ` · ${toppings.map((topping) => topping.name).join(", ")}` : ""}</p><strong>{formatVnd(getUnitPrice(product, item.sizeId, item.toppingIds) * item.quantity)}</strong><div className="cart-item-actions"><QuantityControl onChange={(quantity) => onQuantity(item.key, quantity)} small value={item.quantity} /><button className="remove-button" onClick={() => onRemove(item.key)}>Xóa</button></div></div></article>; })}</div><div className="drawer-summary"><div><span>Tạm tính</span><strong>{formatVnd(subtotal)}</strong></div><p><ClockIcon /> Nhận tại quầy sau khoảng 10–15 phút</p><button className="button button-primary checkout-button" onClick={onCheckout}>Thanh toán <span>{formatVnd(subtotal)}</span></button></div></> : <div className="empty-cart"><span><CartIcon size={32} /></span><h3>Giỏ hàng đang trống</h3><p>Thêm một ly thật ngon để bắt đầu đơn hàng nhé.</p><button className="button button-secondary" onClick={onClose}>Khám phá menu</button></div>}</aside></div>;
}
