import { useState } from "react";
import { formatVnd, getProduct, getUnitPrice } from "../data/products";
import { getServiceFee } from "../domain/orders";
import type { CartItem, PaymentMethod, UserSession } from "../types";
import { ArrowIcon, CheckIcon, ClockIcon, UserIcon } from "../shared/icons";

export default function CheckoutPage({ items, session, onBack, onPay }: { items: CartItem[]; session: UserSession; onBack: () => void; onPay: (method: PaymentMethod, subtotal: number, serviceFee: number) => Promise<void> }) {
  const [method, setMethod] = useState<PaymentMethod>("wallet"); const [confirmed, setConfirmed] = useState(false); const [paying, setPaying] = useState(false);
  const subtotal = items.reduce((total, item) => { const product = getProduct(item.productId); return product ? total + getUnitPrice(product, item.sizeId, item.toppingIds) * item.quantity : total; }, 0); const serviceFee = getServiceFee(subtotal);
  const submit = async () => { if (!confirmed || paying) return; setPaying(true); await onPay(method, subtotal, serviceFee); };
  return <main className="page shell"><button className="back-button" onClick={onBack}><ArrowIcon left /> Quay lại menu</button><div className="checkout-heading"><span className="eyebrow"><span /> Bước cuối cùng</span><h1>Thanh toán đơn hàng</h1><p>Kiểm tra lại món và chọn phương thức thanh toán phù hợp.</p></div><div className="checkout-layout"><section className="checkout-main"><div className="checkout-card pickup-card"><span className="step-number">1</span><div><h2>Nhận tại quầy</h2><p>BrewLite · 273 An Dương Vương, Quận 5</p><span><ClockIcon /> Dự kiến sẵn sàng trong 10–15 phút</span></div></div><div className="checkout-card"><div className="card-title"><span className="step-number">2</span><div><h2>Phương thức thanh toán</h2><p>Chọn cách bạn muốn thanh toán</p></div></div><div className="payment-options">{([['wallet','W','Ví điện tử','MoMo, ZaloPay hoặc VNPay'],['card','••','Thẻ ngân hàng','Visa, Mastercard hoặc thẻ nội địa']] as const).map(([id, icon, title, detail]) => <label className={method === id ? "selected" : ""} key={id}><input checked={method === id} name="payment" onChange={() => setMethod(id)} type="radio" /><span className={`payment-icon ${id === "card" ? "card" : ""}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><span className="radio-dot" /></label>)}</div></div><label className="confirm-check"><input checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} type="checkbox" /><span className="fake-check">{confirmed && <CheckIcon size={14} />}</span><span>Tôi đã kiểm tra thông tin đơn hàng và đồng ý thanh toán.</span></label></section><aside className="order-summary"><div className="summary-title"><h2>Đơn của bạn</h2><span>{items.reduce((sum, item) => sum + item.quantity, 0)} món</span></div><div className="summary-user"><UserIcon /><div><span>Đặt bởi</span><strong>{session.name}</strong></div></div><div className="summary-items">{items.map((item) => { const product = getProduct(item.productId); return product ? <div key={item.key}><img alt="" src={product.imageUrl} /><div><strong>{product.name}</strong><span>{item.quantity} × Size {item.sizeId}</span></div><strong>{formatVnd(getUnitPrice(product, item.sizeId, item.toppingIds) * item.quantity)}</strong></div> : null; })}</div><div className="totals"><div><span>Tạm tính</span><span>{formatVnd(subtotal)}</span></div><div><span>Phí dịch vụ</span><span>{serviceFee ? formatVnd(serviceFee) : <em>Miễn phí</em>}</span></div><div className="total-line"><strong>Tổng cộng</strong><strong>{formatVnd(subtotal + serviceFee)}</strong></div></div><button className="button button-primary pay-button" disabled={!confirmed || paying} onClick={submit}>{paying ? <span className="spinner" /> : <>Thanh toán {formatVnd(subtotal + serviceFee)} <ArrowIcon /></>}</button><p className="secure-note"><span>✓</span> Thanh toán an toàn và được bảo mật</p></aside></div></main>;
}
